### PR TITLE
Add new widgets

### PR DESCRIPTION
**Pull request by XpycT**
vuido control gallery

- [x] Group container
- [x] Checkbox
- [x] ColorButton
- [x] DatePicker
- [x] TimePicker
- [x] DateTimePicker
- [x] FontButton
- [x] Separator
- [x] ProgressBar
- [x] RadioButtons
- [x] Slider
- [x] Tabs

Note: libui-node don't have events for DatePicker, TimePicker and DateTimePicker

### CODE REVIEW

**Comment by mimecorg** [comment]
Great job! Are you planning to add more widgets? We should coordinate this, so that we don’t accidentally work on the same thing.

**Comment by XpycT** [comment]
First of all, thanks for the great project. And yes, I planned to add basically all the widgets. While added a list of next widgets in the first comment.

P.S. English not my first language, so sorry if i'll make mistake :)

**Comment by XpycT** [comment]
ok

**Comment by XpycT** [comment]
That's all for now :smile:

**Comment by mimecorg** [comment]
Thanks a lot @XpycT, I really appreciate it! I will merge it tomorrow and I will release a new version around next Monday-Tuesday.

**Pull request merged**
